/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: Enshin (https://sketchfab.com/enshin)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/cupped-pearl-milk-tea-e3f056696c2d4893bae2b65467b5bcc8
title: タピオカ・ミルクティー(Cupped Pearl Milk Tea)
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { useFrame } from "@react-three/fiber";

export default function Model({ ...props }) {
  const group = useRef();
  const { nodes, materials } = useGLTF("/milk-tea.gltf");
  useFrame(() => {
    group.current.rotation.y += 0.005;
  });
  return (
    <group ref={group} {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]} scale={3}>
          <mesh
            geometry={nodes.defaultMaterial.geometry}
            material={materials.huta_strow}
          />
          <mesh
            geometry={nodes.defaultMaterial_1.geometry}
            material={materials.huta_strow}
          />
          <mesh
            geometry={nodes.defaultMaterial_2.geometry}
            material={materials.nakami}
          />
          <mesh
            geometry={nodes.defaultMaterial_3.geometry}
            material={materials.nakami}
          />
          <mesh
            geometry={nodes.defaultMaterial_4.geometry}
            material={materials.bottle}
          />
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/milk-tea.gltf");
