/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function Model({ ...props }) {
  const group = useRef();
  const { nodes, materials } = useGLTF("/teapot.gltf");
  return (
    <group ref={group} {...props} dispose={null} scale="0.9">
      <mesh
        geometry={nodes.Teapot001.geometry}
        material={nodes.Teapot001.material}
      />
    </group>
  );
}

useGLTF.preload("/teapot.gltf");
